project:
  type: book
  output-dir: docs

book:
  title: "R Projects"
  author: "Sarah Albalawi"
  date: "10/28/2025"
  chapters:
    - index.qmd
    - project_06.qmd
    - project_05.qmd
    - project_04.qmd
    - project_03.qmd
    - project_02.qmd
    - project_01.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand


editor: visual

